name: tests
on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run Unit Tests
        run: | 
          go test -cover ./...
